sudo: required

language: bash

services:
  - docker

install:
  - docker-compose build tests

script:
  - docker-compose run --rm tests

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
