sudo: required

language: php

services:
  - docker
  - php

php:
- '5.6'

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php .
  - ./vendor/bin/phpunit
  - ./vendor/bin/test-reporter

after_success:
  - docker build -t google-drive-extractor .
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
