app:
  build: .
  volumes:
    - .:/code
  working_dir: /code
  entrypoint: ./phpunit.sh
  tty: true
  stdin_open: true
  environment:
    CLIENT_ID: $CLIENT_ID
    CLIENT_SECRET: $CLIENT_SECRET
    ACCESS_TOKEN: $ACCESS_TOKEN
    REFRESH_TOKEN: $REFRESH_TOKEN
    CODECLIMATE_REPO_TOKEN: $CODECLIMATE_REPO_TOKEN
